# tasks file for ubuntu-2004-letsencrypt
---
- name: configuration | copy configuration file
  template:
    src: etc/letsencrypt/cli.ini.j2
    dest: "/etc/letsencrypt/cli.ini"

- name: configuration | create acme challenges directory
  file:
    path: "{{ ubuntu_2004_letsencrypt_webroot_path }}/{{ ubuntu_2004_letsencrypt_acme_challenge_path }}"
    state: directory

- include: configuration-apache.yml
  when: ubuntu_2004_letsencrypt_webroot_webserver is defined and ubuntu_2004_letsencrypt_webroot_webserver == 'apache'

- include: configuration-nginx.yml
  when: ubuntu_2004_letsencrypt_webroot_webserver is defined and ubuntu_2004_letsencrypt_webroot_webserver == 'nginx'
